// Generates a `fancy` wrapper script under ~/.fancy-loop/bin and injects it into the spawned agent's PATH.
// Agents call `fancy ...` from their shell/bash tool → routed to this repo's CLI.
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";

export function ensureFancyBin(): string {
  const dir = path.join(os.homedir(), ".fancy-loop", "bin");
  fs.mkdirSync(dir, { recursive: true });

  const here = path.dirname(fileURLToPath(import.meta.url)); // .../src/daemon
  const cliPath = path.resolve(here, "../cli/index.ts");
  const projectRoot = path.resolve(here, "../.."); // .../fancy-loop
  const tsxBin = path.join(projectRoot, "node_modules", ".bin", "tsx");
  const runner = fs.existsSync(tsxBin) ? tsxBin : "npx tsx"; // prefer local tsx, fallback to npx

  const wrapper = path.join(dir, "fancy");
  const sh = `#!/bin/sh\n# fancy-loop agent CLI wrapper (auto-generated by daemon)\nexec ${runner.includes(" ") ? runner : JSON.stringify(runner)} ${JSON.stringify(cliPath)} "$@"\n`;
  fs.writeFileSync(wrapper, sh);
  fs.chmodSync(wrapper, 0o755);
  return dir;
}
